/// <reference lib="esnext.disposable" preserve="true" />

export {
  ComponentSourceDefaultSchema,
  ComponentSourceRequestSchema,
  ComponentSourceResolvedSchema,
  ComponentSourceResultSchema,
  ComponentSourceResultsSchema,
  ComponentSourceUnresolvedReasonSchema,
  ComponentSourceUnresolvedSchema,
  type ComponentSourceDefault,
  type ComponentSourceRequest,
  type ComponentSourceResolved,
  type ComponentSourceResult,
  type ComponentSourceResults,
  type ComponentSourceUnresolved,
  type ComponentSourceUnresolvedReason,
  ProjectExtractor,
  type ExtractionResult,
  type ProjectExtractorService,
  BackendError,
  ConfigError,
  ExtractError,
  FileNotInProgramError,
  ExtractionResultSchema,
  ModuleNodeSchema,
  SemanticTypeSchema,
  type CallSignatureNode,
  type ArrayNode,
  type ClassMethod,
  type ClassNode,
  type ClassProperty,
  type ComponentNode,
  type ConstructSignatureNode,
  type Documentation,
  type DocumentationTag,
  type EnumMember,
  type EnumNode,
  type ExportNode,
  type ExternalTypeNode,
  type FunctionNode,
  type IntrinsicName,
  type IntrinsicNode,
  type IntersectionNode,
  type IndexSignatureNode,
  type LiteralNode,
  type ModuleNode,
  type ObjectNode,
  type ParameterNode,
  type PropertyNode,
  type SemanticType,
  type TupleNode,
  type TypeArgument,
  type TypeOperatorNode,
  type TypeOperatorResolutionKind,
  type TypeParameterNode,
  type TypeQueryNode,
  type TypeName,
  type UnionNode,
  defaultExtractorOptions,
  type ExtractorOptions,
  type OpenProjectOptions,
  type ProjectFileSystem,
  type ProjectFileSystemEntries,
  type ShouldIncludeData,
  type ShouldResolveObjectData,
  DeclarationOwnerSchema,
  ProvenanceDeclarationSchema,
  ProvenanceEntrySchema,
  ProvenanceSchema,
  type DeclarationOwner,
  type ProvenanceDeclaration,
  type ProvenanceEntry,
  ExtractWarningSchema,
  MissingDefaultExportSymbolWarningSchema,
  MissingEnumDeclarationWarningSchema,
  OmittedCallableMembersWarningSchema,
  OmittedIndexSignatureWarningSchema,
  UncertainComponentRecognitionWarningSchema,
  UnrepresentedConstructSignaturesWarningSchema,
  UnresolvedReExportWarningSchema,
  UnsupportedTypeFallbackWarningSchema,
  type ExtractWarning,
  type MissingDefaultExportSymbolWarning,
  type MissingEnumDeclarationWarning,
  type OmittedCallableMembersWarning,
  type OmittedIndexSignatureReason,
  type OmittedIndexSignatureWarning,
  type TypeFlagName,
  type UncertainComponentRecognitionReason,
  type UncertainComponentRecognitionWarning,
  type UnrepresentedConstructSignaturesWarning,
  type UnresolvedReExportReason,
  type UnresolvedReExportWarning,
  type UnsupportedTypeFallbackWarning,
} from "@elmeragroup/api-extractor";
